### ISSUE TITLE
visualise: missing arguments

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#136]
- [x] zlim
- [x] zlim_contrast
- [x] title

**Comment by teunbrand** [comment]
One of the benefits from getting rid of gridExtra in favour of facetted plots was that users can still modify the plot after visualisation. Is it too much to expect users to be able to do the following?

```
visualise(results) + ggtitle("My title here")
```

or

```
visualise(results) + labs(title = "My title here")
```

The colour limits I understand because ggplot throws warnings when overriding already existing scales, which is not ideal. However, I think `zlim` is too non-descriptive for no other reason than that `image()` uses this argument to control the colour of whatever you put in the `z` argument. If we were plotting in 3 dimensions with 3 axes, then I would understand `zlim` intuitively but it makes little sense in terms of colours to me outside the context of `image()`. 

Alternative suggestions: `col_lim`/`col_lim_contrast`, `colour_lim`/`colour_lim_contrast`, `col_limits`/`col_limits_contrast`, `fill_lim`/`fill_lim_contrast`, `data_lim`/`contrast_lim`, or you could even use one argument `limits = c(0, 40, -10, 10)` wherein the 1st and 2nd values are for the data and the 3rd and 4th for the contrast.

Another consideration is how to handle divergent colourscales with user defined limits. For example, you'd like log2 fold changes and differences to be centered around 0, whereas observed / expected to be centered on 1.

**Comment by robinweide** [comment]
> One of the benefits from getting rid of gridExtra in favour of facetted plots was that users can still modify the plot after visualisation. Is it too much to expect users to be able to do the following?

![](https://media1.tenor.com/images/e6aa079911ee898d4ec9b5b89f644cc9/tenor.gif?itemid=3363592)

All kidding aside, GENOVA is supposed to be user-friendly to bioinformaticians and novice users. Some of those will be familiar with R's basic plotting functionality and thus would expect to be able to set a title.

> Alternative suggestions: `col_lim`/`col_lim_contrast`, `colour_lim`/`colour_lim_contrast`, `col_limits`/`col_limits_contrast`, `fill_lim`/`fill_lim_contrast`, `data_lim`/`contrast_lim`, or you could even use one argument `limits = c(0, 40, -10, 10)` wherein the 1st and 2nd values are for the data and the 3rd and 4th for the contrast.

Very good points. The `colour_lim`/`colour_lim_contrast` option sounds very nice.

> Another consideration is how to handle divergent colourscales with user defined limits. For example, you'd like log2 fold changes and differences to be centered around 0, whereas observed / expected to be centered on 1.

Let's make this the issue of the user: if the user sets `colour_lim_contrast` to c(0,1) for lfc, thats their decision.

**Comment by teunbrand** [comment]
> Some of those will be familiar with R's basic plotting functionality and thus would expect to be able to set a title.

Should these then not use the base R plotting variant for plot methods? I.e. `plot.RCP_discovery()` methods etc., once we've written them.

**Comment by teunbrand** [comment]
Closing this as this should be fixed now.
