### ISSUE TITLE
Use row-names for regions in aggregate-functions.

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#156]
To make life easier and less complicated, we should add the query-regions to the output of the APA, ARA ,etc.

This will look a bit like this:

```
                                 WT   KO1    KO2
--------------------------------------------------------
chr1:1007-1017;chr1:1107-1117    1    1.1    1.2
```

To do:

- [x] APA (in 2019)
- [x] ARA (in 2020)
- [x] ATA (in 2020)
- [x] PE-SCAn (in 2020)
- [ ] saddle (in 2020)
- [x] C-SCAn

Please make sure that all downstream methods still function and propagate the row-names.

**Comment by teunbrand** [comment]
What would this look like for the saddle function? Currently, this returns per-chromosome output.

**Comment by robinweide** [comment]
Saddle would have something like:
```
                                    WT   KO1    KO2
--------------------------------------------------------
Quantile1_vs_Quantile_1   2    2.1    2.2
Quantile1_vs_Quantile_50   1    1.1    1.2
```

**Comment by teunbrand** [comment]
While trying to implement this, I ran into the following problems.

* Rownames must be unique data.frames (data.tables don't support rownames). This is problematic, since the same quantile nr. vs quantile nr. is reported multiple times for different chromosome arms and samples.
* The `q1` and `q2` columns already describe what would be the rownames, so it seems redundant to me.  Just `paste0("Quantile", discovery$saddle$q1, "_vs_Quantile", discovery$saddle$q2)` and you have the information you want. This was different for ARMLA functions, since they returned bins so the exact positional information was lost.
* Given the first two points, if you make the rownames e.g. `exp1_chr1_quantile1_vs_quantile50`, you capture everything in the output but the mean obs/exp values themselves. This would also make no sense to me because you could reconstruct this information perfectly from the output itself.

Alternatively, I think we might want to consider documenting what the output columns of the analysis function exactly are, so that people can refer to that if they want to do some extra programming with it.

**Comment by teunbrand** [comment]
Opened #186 to discuss the alternative

**Comment by robinweide** [comment]
I agree that is makes little sense. Maybe we should just omit the rownames from this output.

**Comment by teunbrand** [comment]
With the exception of saddle, this now exists in dev.
