### ISSUE TITLE
Saddle plot for trans-interactions

### ISSUE THREAD

**Issue by QianzhaoJ** [robinweide/GENOVA#229]
Hi:
Saddle plot for cis-interactions can reflect the enrichment of intra-compartment, maybe it also can be used to the changes of trans compartment-compartment interactions. Can I use the `saddle` function to achieve it in current version? I didn't find an argument like `type=trans` in `saddle` function, could you give me some suggestions ?
Thanks in advance !
Best wishes
Qianzhao

**Comment by teunbrand** [comment]
Hi there,

Currently we don't have an option in the saddle function to look at trans interactions. 
While I understand why I you might want to look at this, there are a few issues that preclude an extension to the current saddle function.

We cannot really compute compartment scores on trans contacts since the eigendecomposition requires a square, symmetric matrix whereas trans contacts betweeg e.g. chr1-chr2 are neither square nor symmetric. A proxy would be to use the compartment scores computed on cis contacts and use that to divide the data into quantile-quantile bins.

Next, in the `saddle()` function we normalise the contacts for distance from the diagonal by computing the log2(observed/expected), wherein the expected is the mean of a distance from the diagonal. For trans contacts, the distance to the diagonal is meaningless and insensible to normalise with, so the next best thing would be to look at the observed portion only. This would also imply that these are more sensible to local biases compared to normalised values.

If you are still interested in calculating saddle-like scores for trans contacts anyway, I'm afraid that you would have to go the route of manually calculating this for now. The easiest way I see is to follow these steps:

1. Assign per-chromosome quantile bins to the compartment scores
2. Annotate the main data with the chromosome and quantile bin of the [i,j] index.
3. Compute mean of contacts by quantile bin and chromosome combination.

Best wishes,
Teun

**Comment by QianzhaoJ** [comment]
Good idea ! I will try it directly.
Thanks for your help.

Best,
Qianzhao
