### ISSUE TITLE
`data.table` `Error in vecseq...` bug when running RCP

### ISSUE THREAD

**Issue by xscapintime** [robinweide/GENOVA#292]
Hi,

I was trying to add bed files in RCP analysis. I have 3 bed files, using one of them returns this error.

```R
RCP_bed_out <- RCP(list(hic1, hic2), 
                bedlist = bed3)                                     
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 74056983 rows; more than 61094392 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
```

The other two bed files work fine.

I have checked the problematic bed file, there are no duplicated entries.

```shell
wc -l bed3.bed
98573 bed3.bed

cat bed3.bed | cut -f 1,2,3 | uniq |wc -l
98573
```

Any idea/solution/suggestion?

Thanks

**Comment by teunbrand** [comment]
Hi there,

I suspect that there are no duplicate entries in your bed files, but that some regions that are in your bed file fall into the same hi-c bin. You can use the `bed2idx()` function to double-check this and remove any entries that are in the same bin, in the following way:

``` r
library(GENOVA)

exp <- get_test_data("40k")

# 2nd row same Hi-C bin as 1st row
bed <- data.frame(
  chrom = "chr22",
  start = c(51120100, 51120300),
  end   = c(51120200, 51120400)
)

# Find Hi-C bin for every entry
index <- bed2idx(exp$IDX, bed)

# Run RCP without duplicated bins
rcp_out <- RCP(exp, bed[!duplicated(index), ])
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

@robinweide:
I think it is a good idea for us to first deduplicate indices in the internal `RCPbed` function. Otherwise, we're using information twice if two bed entries fall into the same hi-c bin.  Any thoughts?
