### ISSUE TITLE
Add domainogram for Virtual 4C plot?

### ISSUE THREAD

**Issue by Qidong-LI** [robinweide/GENOVA#363]
Thank you for your fantastic package. I have one request: is it possible to add a domainogram for Virtual 4C analysis? I've tried many methods and software, but reshaping the Hi-C data can not match the required input format. Your package gives me hope. Thanks in advance.

Best regards,
Qidong

**Comment by deWitLab** [comment]
Dear Qidong,

Thanks for your email. Do you mean a 4C domainogram (like in Splnter et al) or an insulation domainogram (like the one implemented in GENOVA)?

Best,
Elzo

From: Qidong LI ***@***.***>
Reply to: robinweide/GENOVA ***@***.***>
Date: Tuesday, 8 October 2024 at 09:51
To: robinweide/GENOVA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [robinweide/GENOVA] Add domainogram for Virtual 4C plot? (Issue #363)

LET OP: Deze e-mail is afkomstig van buiten de organisatie. Open alleen links of bijlagen als je de afzender kent en weet dat de inhoud veilig is.
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Thank you for your fantastic package. I have one request: is it possible to add a domainogram for Virtual 4C analysis? I've tried many methods and software, but reshaping the Hi-C data can not match the required input format. Your package gives me hope. Thanks in advance.

Best regards,
Qidong

**Comment by Qidong-LI** [comment]
Dear Elzo,

Thanks for your quick reply and yes, the 4C domainogram like the one I post here. I don't know if it is available to make it in virtual 4C analysis. But I think it is feasible because I have seen Capture Hi-C studies that also used domainograms (https://doi.org/10.1038/ng.3286). If the matrix extracted from the virtual 4C is further observed using different window sizes, the virtual 4C domainogram should be obtained. Looking forward to your reply and thanks again.

Best,

Qidong
![example](https://github.com/user-attachments/assets/c188da1c-f87f-4ea9-a397-a059e79beca9)

**Comment by deWitLab** [comment]
Dear Qidong,

That will be difficult to do in GENOVA, because the the measurements are different (fragment-based vs. bin-based). I guess you should be able to write something based on the data that you extract from the virtual 4C, but this will not be same as what the 4C/Capture-C domainograms achieve. This has not been implemented in GENOVA (and probably will not be implemented, due to the vast differences in scale of the methods).

Best,
Elzo

From: Qidong LI ***@***.***>
Reply to: robinweide/GENOVA ***@***.***>
Date: Wednesday, 9 October 2024 at 09:28
To: robinweide/GENOVA ***@***.***>
Cc: Elzo de Wit ***@***.***>, Comment ***@***.***>
Subject: Re: [robinweide/GENOVA] Add domainogram for Virtual 4C plot? (Issue #363)

LET OP: Deze e-mail is afkomstig van buiten de organisatie. Open alleen links of bijlagen als je de afzender kent en weet dat de inhoud veilig is.
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Dear Elzo,

Thanks for your quick reply and yes, the 4C domainogram like the one I post here. I don't know if it is available to make it in virtual 4C analysis. But I think it is feasible because I have seen Capture Hi-C studies that also used domainograms (https://doi.org/10.1038/ng.3286). If the matrix extracted from the virtual 4C is further observed using different window sizes, the virtual 4C domainogram should be obtained. Looking forward to your reply and thanks again.

Best,

Qidong
example.png (view on web)<https://github.com/user-attachments/assets/c188da1c-f87f-4ea9-a397-a059e79beca9>

**Comment by Qidong-LI** [comment]
Dear Elzo,

OK, Thank you for your suggestion.

Best
